### ISSUE TITLE
bug 反馈 - 使用 Mac 版的 Firefox，首页加载失败

### ISSUE THREAD

**Issue by yfaming** [Jannchie/BiliOB#7]
具体版本：
Mac: 10.15.7
Firefox: 81.0.2 (64-bit)

具体症状是，一直显示「载入中...」。
打开浏览器控制台，显示有语法错误。如下图：

<img src='https://pic1.zhimg.com/80/v2-75dc9b7cf0ef6747c675540035c27dc4_1440w.png'>

PS: 今天才知道这个网站，做得挺好，加油~

**Comment by OpportunityLiu** [comment]
路由写错了吧，加载js直接提供404页面了

**Comment by yfaming** [comment]
> 路由写错了吧，加载js直接提供404页面了

**Comment by yfaming** [comment]
> 路由写错了吧，加载js直接提供404页面了

应该不是这个原因，在 Chrome 上访问的话，一切正常。上面的报错，感觉是 js 压缩相关的问题。

**Comment by OpportunityLiu** [comment]
刷新几次就好了，应该是旧的html页面引用的脚本hash和新的不一样

**Comment by yfaming** [comment]
> 刷新几次就好了，应该是旧的html页面引用的脚本hash和新的不一样

果然好了，神奇！昨天是第一次访问这个网站，感觉不应该有「旧的html页面」啥的。而且昨天我反复尝试了好多次，都不行。
先 close 掉了。

**Comment by OpportunityLiu** [comment]
说不定你访问的时候正在发布新版本，下到了旧的html，然后去拿脚本的时候旧的脚本已经没了
